eps_check_interval: 60          # EPS kontrol etme sıklığı (saniye cinsinden)
log_interval: 1                 # EPS verilerini log dosyasına yazma sıklığı (dakika cinsinden)
post_interval: 1                # POST işlemi yapma sıklığı (dakika cinsinden)
post_url: "https://kcrm.kclogger.com/cron/logControl.php"   # POST işleminin yapılacağı URL
ip: "10.10.44.68"               # IP adresi
musteri: "ngn"                  # Müşteri adı
id: "123"                       # Müşteri ID'si
log_dir: "/var/log/kclogger"     # Log dosyalarının kaydedileceği dizin
